// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire_injectors.go:

func setupDev() (*config, func(), error) {
	passworder := providePassworder()
	fmodeler := provideDevModeler(passworder)
	tokenHelper := provideTokenHelper()
	mailSender := provideDevMailSender()
	apiHelper := provideAPI()
	lister := provideLister()
	mainConfig := newConfig(fmodeler, tokenHelper, mailSender, apiHelper, lister)
	return mainConfig, func() {
	}, nil
}

func setupProd() (*config, func(), error) {
	passworder := providePassworder()
	fmodeler, err := provideProdModeler(passworder)
	if err != nil {
		return nil, nil, err
	}
	tokenHelper := provideTokenHelper()
	mailSender := provideProdMailSender()
	apiHelper := provideAPI()
	lister := provideLister()
	mainConfig := newConfig(fmodeler, tokenHelper, mailSender, apiHelper, lister)
	return mainConfig, func() {
	}, nil
}
