// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "my-inventory": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/NBR41/go-testgoa/design
// --out=$(GOPATH)/src/github.com/NBR41/go-testgoa
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// BooksHref returns the resource href.
func BooksHref(bookID interface{}) string {
	parambookID := strings.TrimLeftFunc(fmt.Sprintf("%v", bookID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/books/%v", parambookID)
}

// OwnershipsHref returns the resource href.
func OwnershipsHref(userID, bookID interface{}) string {
	paramuserID := strings.TrimLeftFunc(fmt.Sprintf("%v", userID), func(r rune) bool { return r == '/' })
	parambookID := strings.TrimLeftFunc(fmt.Sprintf("%v", bookID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/users/%v/ownerships/%v", paramuserID, parambookID)
}

// UsersHref returns the resource href.
func UsersHref(userID interface{}) string {
	paramuserID := strings.TrimLeftFunc(fmt.Sprintf("%v", userID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/users/%v", paramuserID)
}
