// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "my-inventory": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/NBR41/go-testgoa/design
// --out=$(GOPATH)/src/github.com/NBR41/go-testgoa
// --version=v1.2.0-dirty

package test
